@startuml
[Main] --> printVSLogic
printVSLogic .left.> [modification]

printVSLogic <--> [user_interaction]

printVSLogic <..> [configuration]

[user_interaction] ..> [CrasswordFactory]
[user_interaction] ..> [Game]


@enduml