= Модуль конфигурации кроссворда

Этот модуль направлен на постороение наиболее оптимального возможного варианта кроссворда. +
Из списка введенных пользователем слов составляется кроссворд методом перебора возможных вариантов. Если по окончании 30 сек не был закончен перебор всех возможных вариантов создания, то выбирается наиболее оптимальный из уже составленных (который использует наибольшее количество слов). +

Для каждого варианта расположения слов используется матрица, размера, заданного пользователем, который вводил слова. Каждая клетка матрицы хранит номер вертикального и горизонтального слов, проходящих через эту клетку. +

=== Заполнение матрицы +

Для того чтобы вставить слово в матрицу, надо найти для него место. Сначала находится шаблон для горизонтального слова, затем осуществляется поиск слова, удовлетворяющего шаблону. +

NOTE: Шаблон для вертикального слова содержит в себе информацию о длинне слова и список уже занятых мест горизонтальным словом (номер позиции и буква на этой позиции). Для горизонтальных слов шаблон аналогичен.

Следующая за последней буквой слова клетка помечается как черная (и в неё уже нельзя ничего добавлять, ни по горизонтали, ни по вертикали). Далее делаем поиск горизонтального шаблона для каждой буквы. Если слово под шаблон не найдено, то клетка, следующая в столбце после первой клетки шаблона, занятой горизонтальным словом,помечается черным.

После пребора всех возможных мест вставки слова матрицы, проверяется оптимальность созданного кроссворда. +

=== Проверка оптимальности

Если в кроссворде задействованы все слова из списка, то он является оптимальным и продолжение поиска не требуется. Если задействованы не все слова, но больше чем при самой оптимальной из уже существующих конфигураций, то этот вариант сохраняется как наиболее оптимальный на данном этапе. Далее, при условии что время на конфигурацию еще не закончилось, осуществляется поиск следующего возможного варианта. Если время закончено, то выбирается наиболее оптимальный на данный момент кроссворд. +


== Диаграмма классов

[plantuml,format="png"]
--
include::..analysis\diagrams\Config.puml[]
--

Класс *Configurator* используется для построения кроссворда. С помощью метода *findOptimalMatrix()* прозводится поиск матрицы (которая является полем кроссворда), метод *checkOptimal()* проверяет матрицу на оптимальность. Методом *getCrossword()* можно получить кроссворд. +
Класс *Matrix* направлен на хранение и создание матрицы. +
Класс *Cell* обрабатывает клетки матрицы. Каждая клетка хранит номер горизонтального и вертикального слова, а также общий символ. +
Метод *fillingMatrix()* класса Matrix добавляет слова в матрицу, тем самым заполняя поле кроссворда. Он создаёт объект класса *Scheme*, который содержит в себе схему слова, которое можно добавить следующим. Этот объект передатся в функцию *findWord(Scheme sc,ArrayList<String> words)* класса FindingWord для нахождения слова, удовлетворяющего заданным ограничениям. +
Класс *Constrains* обрабатывает каждое ограничение на слово.