= Модуль взаимодействия с пользователем

В данной задаче есть два режима: создания кроссворда и его решения (игры). +
При запуске программы пользователь выбирает нужный ему режим. +

== При выборе режима создания кроссворда +
При выборе режима создания кроссворда у пользователя будет запрошен ввод размера поля, а зетем список слов. Если какое-то слово не будет подходит заданному ограничению (размер слова больше размера поля), то будет выведено сообщение об этом. +
После окончания ввода слов, пользователю предлагается составить кроссворд. Если он подтвержает, то программа моделирует кроссворд из списка введенных слов. +

== При выборе режима решения кроссворда +
При выборе режима решения кроссворда пользователю предлагается решить кроссворд. Когда он захочет проверить кроссворд, он может нажать esc (будет уточнено) и ему выведется результат (правильно решён кроссворд или нет). +

== Диаграмма классов

[plantuml,format="png"]
--
include::\\analysis\diagrams\UserInteraction.puml[]
--

Класс *UserMenu* используется для выбора режима. При вызове метода *CrosswordMode* пользователю будет предложено выбрать один из двух режимов. +

При выборе режима создания кроссоворда будет создан объект класса *CrosswordFactory* и вызван его метод *startMode*. В этом методе будут вызваны другие методы класса для создания списка слов и списка описаний. Список слов состоит из объектов типа *Word* - это класс, с помощью которого можно запрашивать новое слово и добавлять его в список, при условии если метод *isFitted*, который проверяет удовлетворяет ли слово условиям, вернёт true. +

При выборе режима игры будет создан объект класса *Game* и вызван его метод *startMode*. С помощью метода *print()*, который вызывает *printCrosswordMap()* и *printDescription()*, будет напечатан кроссворд. Далее, он проверяется с помощью метода *compareCrossword(CrossworsFactory cr)* и печатается результат с помощью *printResult()*.
